os:
  - linux

language: go

go:
  - 1.13.x

env:
  global:
    - BUILD_DEPTYPE=gomod
  matrix:
    - GOTFLAGS="-race"
    - GOTFLAGS="-race -tags=openssl"

# disable travis install
install:
  - true

script: bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

jobs:
  include:
    - stage: "Test"
      script: "./tools/compat-check"
      name: "API compatibility test"
      env:
        - GOTFLAGS=""


cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
